### ISSUE TITLE
MAnorm output

### ISSUE THREAD

**Issue by catch-minie** [ying-w/chipseq-compare#2]
I have a question regarding results of MAnorm , the result contains following header :
chr	start	end	description	#raw_read_1	#raw_read_2	M_value_rescaled	A_value_rescaled	-log10(p-value)

I want to know the detail about column raw_read1 & raw_read2 , what does it refers to?

**Comment by ying-w** [comment]
Using bedtools intersect bed to count how many reads overlap each region as defined by the bed file. This would be the raw counts that get fed into the MA adjustment.

**Comment by catch-minie** [comment]
And Wat is the MA adjustment ?

**Comment by ying-w** [comment]
have a look at either the [original paper](https://www.ncbi.nlm.nih.gov/pubmed/22424423) or [my comparison paper](https://www.ncbi.nlm.nih.gov/pubmed/25972895)

the main idea is assuming shared peaks are non-differential and normalizing all peaks to shared peaks. This assumption sometimes holds and sometimes doesn't depending on what kind of cells are being compared.
