### ISSUE TITLE
MAnorm3.R issue 

### ISSUE THREAD

**Issue by catch-minie** [ying-w/chipseq-compare#3]
I am facing following issue while running MAnorm3.R 

ls: cannot access './chk/*xls': No such file or directory
../MAnorm3.sh: 414: ../MAnorm3.sh: [[: not found
MAnorm3.R did not create excel output file check chk_Rcommand.out
 no excel file is generated , any idea why?

**Comment by ying-w** [comment]
Please make sure you have bash shell installed `which $SHELL` should return `/bin/bash/`

**Comment by catch-minie** [comment]
Its returning /bin/bash upon typing which $SHELL.

**Comment by ying-w** [comment]
could you type in `echo $SHELL` and `$SHELL --version` also see [here](http://stackoverflow.com/questions/12230690/string-comparison-in-bash-not-found)

**Comment by catch-minie** [comment]
Here is the output

GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by ying-w** [comment]
Try the answer mentioned in the SO post, `bash ./MAnorm3.sh <parameters>` or adding `#!/bin/bash` to the first line of the script

**Comment by catch-minie** [comment]
Hi!
after adding #!/bin/bash  also its  showing this error

ls: cannot access './check/*xls': No such file or directory
MAnorm3.R did not create excel output file check check_Rcommand.out

Can you gv me some other alternative?

**Comment by ying-w** [comment]
Could you email me the check_Rcommand.out file as well as ensure that bedtools is installed?

**Comment by catch-minie** [comment]
Here it is:
[check_Rcommand.txt](https://github.com/ying-w/chipseq-compare/files/726724/check_Rcommand.txt)

**Comment by ying-w** [comment]
I think either common peaks or empty or maybe something weird going on with your matrix (all 0s?) Could you attach the *log file as well double checking that the counts file are not all empty?

**Comment by catch-minie** [comment]
[check_log.txt](https://github.com/ying-w/chipseq-compare/files/729021/check_log.txt)
Here is the log file,its not emtry but it has all 0s.

simultaneously, on the other hand I am running MAnorm with merged replicate data , one set worked fine, the other one is throwing error with all 0s in common_peak_count_read2 file.

**Comment by kminie** [comment]
I am getting one wired error , like this-
 Error: line number 157951095 of file read2.bed has 6 fields, but 3 were expected.
Error: line number 136338639 of file read1.bed has 6 fields, but 3 were expected.
Error: line number 157951095 of file read2.bed has 6 fields, but 3 were expected

this has never come before

**Comment by catch-minie** [comment]
Hi , did you find out something regarding this the above mentioned problem?

**Comment by ying-w** [comment]
Are you not having any peaks in common between the two conditions? MA norm isn't going to work if you have no common peaks between conditions or all your peaks are common.

The log file that you sent, it seems like all the reads were caught by a filter and excluded. Are you using human sequence? Do you use `chr1` or `1` naming format for reference? I currently have my script filter all chromosomes that don't have `chr` to exclude things like bait. It seems kind of weird that one work but the other didn't. Are you mapping to the same reference?

**Comment by catch-minie** [comment]
The problem with common peaks is solved but the problem with MAnorm3.r is still there any inputs on this?

**Comment by ying-w** [comment]
The check_Rcommand.txt file shows that the error in R is due to something being wrong w/the counts matrix (all 0s). Make sure the counts matrix makes sense (not empty, not all 0s for both common and unique peak regions), rerun the shell script (MAnorm3.sh) so that it would re-generate the counts files and then the error in R script should go away.
