### ISSUE TITLE
Error Output: ls: cannot access ./BB4_Int_Kid/*xls: No such file or directory

### ISSUE THREAD

**Issue by s-luo** [ying-w/chipseq-compare#5]
Hi, I've been working on a project that explores different binding patterns in intestine and kidney tissue. Your method, MAnorm3, is one of several methods that am using for my research. However, I seem to be running into this error of it not being able to open the excel file/it doesn't exist. 

This is everything if the error output file:
ls: cannot access ./BB4_Int_Kid/*xls: No such file or directory
srun: error: hal0037: task 0: Exited with exit code 1

Thanks
S. Luo

**Comment by ying-w** [comment]
answered in email
